#!/command/with-contenv bash
# shellcheck shell=bash

echo "Starting BookBagOfHolding..."

exec \
    s6-setuidgid abc /lsiopy/bin/python3 /app/bookbagofholding/BookBagOfHolding.py \
    --datadir /config --nolaunch
