#!/command/with-contenv bash
# shellcheck shell=bash

echo "Starting LazyLibrarian..."

exec \
    s6-setuidgid abc /lsiopy/bin/python3 /app/lazylibrarian/LazyLibrarian.py \
    --datadir /config --nolaunch
